# Spring Boot Configuración General

# Puerto donde corre la app
server.port=8080

# Rutas para JSP
server.error.whitelabel.enabled=false
server.error.path=/error
spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp


# Base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/residuos_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA y Hibernate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Codificación por defecto
server.servlet.encoding.charset=UTF-8
server.servlet.encoding.enabled=true
server.servlet.encoding.force=true